/******************************************************************************
 * Copyright 2021 TypeFox GmbH
 * This program and the accompanying materials are made available under the
 * terms of the MIT License, which is available in the project root.
 ******************************************************************************/

import { inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices } from 'langium/lsp';
import { SimpleDslGeneratedModule, SimpleDslGeneratedSharedModule } from './generated/module.js';

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SimpleDslServices = LangiumServices

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSimpleDslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    simpleDsl: SimpleDslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SimpleDslGeneratedSharedModule
    );
    const simpleDsl = inject(
        createDefaultModule({ shared }),
        SimpleDslGeneratedModule
    );
    shared.ServiceRegistry.register(simpleDsl);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, simpleDsl };
}
